
	 
	/*
	 *	This content is generated from the API File Info.
	 *	(Alt+Shift+Ctrl+I).
	 *
	 *	@desc 		
	 *	@file 		enter_id
	 *	@date 		Thursday 25th of April 2024 10:03:48 AM
	 *	@title 		Page 1
	 *	@author 	
	 *	@keywords 	
	 *	@generator 	Export Kit v1.3.figma
	 *
	 */
	

package pfe.africar.activitys;

import android.app.Activity;
import android.os.Bundle;


import android.view.View;
import android.widget.TextView;
import android.widget.ImageView;

import pfe.africar.R;

	public class academics_activity extends Activity {

	
	private View _bg__academics_ek2;
	private TextView academics_ek3;
	private View _bg__frame_106_ek1;
	private View _bg__frame_103_ek1;
	private View _bg__teacher_rafiki_ek1;
	private View _bg__freepik__background_complete__inject_2_ek1;
	private ImageView vector_ek108;
	private ImageView vector_ek109;
	private ImageView vector_ek110;
	private ImageView vector_ek111;
	private ImageView vector_ek112;
	private ImageView vector_ek113;
	private ImageView vector_ek114;
	private ImageView vector_ek115;
	private ImageView vector_ek116;
	private ImageView vector_ek117;
	private ImageView vector_ek118;
	private ImageView vector_ek119;
	private ImageView vector_ek120;
	private ImageView vector_ek121;
	private ImageView vector_ek122;
	private ImageView vector_ek123;
	private ImageView vector_ek124;
	private ImageView vector_ek125;
	private ImageView vector_ek126;
	private ImageView vector_ek127;
	private ImageView vector_ek128;
	private ImageView vector_ek129;
	private ImageView vector_ek130;
	private View _bg__freepik__shadow__inject_2_ek1;
	private ImageView freepik__path__inject_2;
	private View _bg__freepik__board__inject_2_ek1;
	private ImageView vector_ek131;
	private ImageView vector_ek132;
	private View _bg__group_ek35;
	private ImageView vector_ek133;
	private ImageView vector_ek134;
	private ImageView vector_ek135;
	private ImageView vector_ek136;
	private ImageView vector_ek137;
	private ImageView vector_ek138;
	private ImageView vector_ek139;
	private ImageView vector_ek140;
	private TextView b;
	private TextView b_ek1;
	private TextView c;
	private TextView c_ek1;
	private TextView a;
	private TextView a_ek1;
	private ImageView vector_ek141;
	private ImageView vector_ek142;
	private ImageView vector_ek143;
	private ImageView vector_ek144;
	private ImageView vector_ek145;
	private ImageView vector_ek146;
	private ImageView vector_ek147;
	private ImageView vector_ek148;
	private ImageView vector_ek149;
	private ImageView vector_ek150;
	private ImageView vector_ek151;
	private ImageView vector_ek152;
	private ImageView vector_ek153;
	private ImageView vector_ek154;
	private ImageView vector_ek155;
	private ImageView vector_ek156;
	private ImageView vector_ek157;
	private ImageView vector_ek158;
	private ImageView vector_ek159;
	private ImageView vector_ek160;
	private ImageView vector_ek161;
	private ImageView vector_ek162;
	private ImageView vector_ek163;
	private ImageView vector_ek164;
	private ImageView vector_ek165;
	private ImageView vector_ek166;
	private ImageView vector_ek167;
	private View _bg__freepik__teacher__inject_2_ek1;
	private ImageView vector_ek168;
	private ImageView vector_ek169;
	private ImageView vector_ek170;
	private ImageView vector_ek171;
	private ImageView vector_ek172;
	private ImageView vector_ek173;
	private ImageView vector_ek174;
	private ImageView vector_ek175;
	private ImageView vector_ek176;
	private ImageView vector_ek177;
	private ImageView vector_ek178;
	private ImageView vector_ek179;
	private ImageView vector_ek180;
	private ImageView vector_ek181;
	private ImageView vector_ek182;
	private ImageView vector_ek183;
	private ImageView vector_ek184;
	private ImageView vector_ek185;
	private ImageView vector_ek186;
	private ImageView vector_ek187;
	private ImageView vector_ek188;
	private ImageView vector_ek189;
	private ImageView vector_ek190;
	private ImageView vector_ek191;
	private ImageView vector_ek192;
	private ImageView vector_ek193;
	private ImageView vector_ek194;
	private ImageView vector_ek195;
	private ImageView vector_ek196;
	private ImageView vector_ek197;
	private ImageView vector_ek198;
	private ImageView vector_ek199;
	private ImageView vector_ek200;
	private ImageView vector_ek201;
	private ImageView vector_ek202;
	private ImageView vector_ek203;
	private ImageView vector_ek204;
	private ImageView vector_ek205;
	private ImageView vector_ek206;
	private ImageView vector_ek207;
	private ImageView vector_ek208;
	private ImageView vector_ek209;
	private ImageView vector_ek210;
	private ImageView vector_ek211;
	private ImageView vector_ek212;
	private ImageView vector_ek213;
	private ImageView vector_ek214;
	private View _bg__freepik__table__inject_2_ek1;
	private ImageView vector_ek215;
	private ImageView vector_ek216;
	private ImageView vector_ek217;
	private ImageView vector_ek218;
	private ImageView vector_ek219;
	private ImageView vector_ek220;
	private ImageView vector_ek221;
	private ImageView vector_ek222;
	private ImageView vector_ek223;
	private ImageView vector_ek224;
	private ImageView vector_ek225;
	private ImageView vector_ek226;
	private ImageView vector_ek227;
	private ImageView vector_ek228;
	private ImageView vector_ek229;
	private ImageView vector_ek230;
	private ImageView vector_ek231;
	private ImageView vector_ek232;
	private ImageView vector_ek233;
	private View _bg__freepik__student__inject_2_ek1;
	private View _bg__freepik__group__inject_2_ek1;
	private ImageView vector_ek234;
	private ImageView vector_ek235;
	private ImageView vector_ek236;
	private ImageView vector_ek237;
	private ImageView vector_ek238;
	private ImageView vector_ek239;
	private ImageView vector_ek240;
	private ImageView vector_ek241;
	private ImageView vector_ek242;
	private ImageView vector_ek243;
	private ImageView vector_ek244;
	private ImageView vector_ek245;
	private ImageView vector_ek246;
	private ImageView vector_ek247;
	private ImageView vector_ek248;
	private ImageView vector_ek249;
	private ImageView vector_ek250;
	private ImageView vector_ek251;
	private ImageView vector_ek252;
	private ImageView vector_ek253;
	private ImageView vector_ek254;
	private ImageView vector_ek255;
	private ImageView vector_ek256;
	private ImageView vector_ek257;
	private ImageView vector_ek258;
	private ImageView vector_ek259;
	private ImageView vector_ek260;
	private ImageView vector_ek261;
	private ImageView vector_ek262;
	private View _bg__freepik__chair__inject_2_ek1;
	private ImageView vector_ek263;
	private ImageView vector_ek264;
	private ImageView vector_ek265;
	private ImageView vector_ek266;
	private ImageView vector_ek267;
	private ImageView vector_ek268;
	private ImageView vector_ek269;
	private ImageView vector_ek270;
	private ImageView vector_ek271;
	private ImageView vector_ek272;
	private ImageView vector_ek273;
	private ImageView vector_ek274;
	private View _bg__group_ek37;
	private ImageView vector_ek275;
	private View _bg__group_ek39;
	private ImageView vector_ek276;
	private ImageView vector_ek277;
	private ImageView vector_ek278;
	private ImageView vector_ek279;
	private ImageView vector_ek280;
	private TextView courses_ek13;
	private View _bg__frame_105_ek1;
	private View _bg__customer_survey_rafiki_ek1;
	private View _bg__freepik__background_complete__inject_15_ek1;
	private ImageView vector_ek281;
	private ImageView vector_ek282;
	private ImageView vector_ek283;
	private ImageView vector_ek284;
	private ImageView vector_ek285;
	private ImageView vector_ek286;
	private ImageView vector_ek287;
	private ImageView vector_ek288;
	private ImageView vector_ek289;
	private ImageView vector_ek290;
	private ImageView vector_ek291;
	private ImageView vector_ek292;
	private ImageView vector_ek293;
	private ImageView vector_ek294;
	private ImageView vector_ek295;
	private ImageView vector_ek296;
	private ImageView vector_ek297;
	private ImageView vector_ek298;
	private ImageView vector_ek299;
	private ImageView vector_ek300;
	private ImageView vector_ek301;
	private ImageView vector_ek302;
	private ImageView vector_ek303;
	private ImageView vector_ek304;
	private ImageView vector_ek305;
	private ImageView vector_ek306;
	private ImageView vector_ek307;
	private ImageView vector_ek308;
	private ImageView vector_ek309;
	private ImageView vector_ek310;
	private ImageView vector_ek311;
	private ImageView vector_ek312;
	private ImageView vector_ek313;
	private ImageView vector_ek314;
	private ImageView vector_ek315;
	private ImageView vector_ek316;
	private ImageView vector_ek317;
	private ImageView vector_ek318;
	private ImageView vector_ek319;
	private ImageView vector_ek320;
	private ImageView vector_ek321;
	private ImageView vector_ek322;
	private ImageView vector_ek323;
	private ImageView vector_ek324;
	private ImageView vector_ek325;
	private ImageView vector_ek326;
	private ImageView vector_ek327;
	private View _bg__freepik__shadow__inject_15_ek1;
	private ImageView freepik__path__inject_15;
	private View _bg__freepik__survey__inject_15_ek1;
	private ImageView vector_ek328;
	private ImageView vector_ek329;
	private ImageView vector_ek330;
	private ImageView vector_ek331;
	private View _bg__group_ek41;
	private ImageView vector_ek332;
	private ImageView vector_ek333;
	private ImageView vector_ek334;
	private View _bg__group_ek43;
	private ImageView vector_ek335;
	private ImageView vector_ek336;
	private ImageView vector_ek337;
	private ImageView vector_ek338;
	private View _bg__group_ek45;
	private ImageView vector_ek339;
	private ImageView vector_ek340;
	private ImageView vector_ek341;
	private ImageView vector_ek342;
	private ImageView vector_ek343;
	private ImageView vector_ek344;
	private ImageView vector_ek345;
	private ImageView vector_ek346;
	private ImageView vector_ek347;
	private ImageView vector_ek348;
	private ImageView vector_ek349;
	private ImageView vector_ek350;
	private ImageView vector_ek351;
	private ImageView vector_ek352;
	private ImageView vector_ek353;
	private ImageView vector_ek354;
	private ImageView vector_ek355;
	private ImageView vector_ek356;
	private ImageView vector_ek357;
	private ImageView vector_ek358;
	private ImageView vector_ek359;
	private ImageView vector_ek360;
	private ImageView vector_ek361;
	private ImageView vector_ek362;
	private View _bg__freepik__character__inject_15_ek1;
	private ImageView vector_ek363;
	private ImageView vector_ek364;
	private ImageView vector_ek365;
	private ImageView vector_ek366;
	private ImageView vector_ek367;
	private ImageView vector_ek368;
	private ImageView vector_ek369;
	private ImageView vector_ek370;
	private ImageView vector_ek371;
	private ImageView vector_ek372;
	private ImageView vector_ek373;
	private ImageView vector_ek374;
	private ImageView vector_ek375;
	private ImageView vector_ek376;
	private ImageView vector_ek377;
	private ImageView vector_ek378;
	private ImageView vector_ek379;
	private ImageView vector_ek380;
	private ImageView vector_ek381;
	private ImageView vector_ek382;
	private ImageView vector_ek383;
	private ImageView vector_ek384;
	private ImageView vector_ek385;
	private ImageView vector_ek386;
	private ImageView vector_ek387;
	private ImageView vector_ek388;
	private ImageView vector_ek389;
	private ImageView vector_ek390;
	private ImageView vector_ek391;
	private ImageView vector_ek392;
	private ImageView vector_ek393;
	private ImageView vector_ek394;
	private ImageView vector_ek395;
	private ImageView vector_ek396;
	private ImageView vector_ek397;
	private TextView quizzes_ek10;
	private View _bg__frame_104_ek1;
	private View _bg__chemistry_lab_rafiki_ek1;
	private View _bg__freepik__background_complete__inject_2_ek3;
	private View _bg__group_ek47;
	private View _bg__group_ek49;
	private View _bg__group_ek51;
	private ImageView vector_ek398;
	private ImageView vector_ek399;
	private ImageView vector_ek400;
	private ImageView vector_ek401;
	private ImageView vector_ek402;
	private ImageView vector_ek403;
	private ImageView vector_ek404;
	private ImageView vector_ek405;
	private ImageView vector_ek406;
	private ImageView vector_ek407;
	private ImageView vector_ek408;
	private ImageView vector_ek409;
	private ImageView vector_ek410;
	private View _bg__group_ek53;
	private ImageView vector_ek411;
	private ImageView vector_ek412;
	private View _bg__group_ek55;
	private ImageView vector_ek413;
	private ImageView vector_ek414;
	private View _bg__group_ek57;
	private ImageView vector_ek415;
	private ImageView vector_ek416;
	private View _bg__group_ek59;
	private ImageView vector_ek417;
	private ImageView vector_ek418;
	private View _bg__group_ek61;
	private View _bg__group_ek63;
	private ImageView vector_ek419;
	private ImageView vector_ek420;
	private ImageView vector_ek421;
	private View _bg__group_ek65;
	private View _bg__group_ek67;
	private ImageView vector_ek422;
	private View _bg__group_ek69;
	private ImageView vector_ek423;
	private ImageView vector_ek424;
	private ImageView vector_ek425;
	private ImageView vector_ek426;
	private ImageView vector_ek427;
	private ImageView vector_ek428;
	private ImageView vector_ek429;
	private View _bg__group_ek71;
	private ImageView vector_ek430;
	private ImageView vector_ek431;
	private View _bg__group_ek73;
	private View _bg__group_ek75;
	private ImageView vector_ek432;
	private View _bg__group_ek77;
	private ImageView vector_ek433;
	private ImageView vector_ek434;
	private ImageView vector_ek435;
	private ImageView vector_ek436;
	private ImageView vector_ek437;
	private ImageView vector_ek438;
	private ImageView vector_ek439;
	private View _bg__freepik__shadow__inject_2_ek3;
	private ImageView vector_ek440;
	private View _bg__freepik__picture__inject_2_ek1;
	private View _bg__group_ek79;
	private ImageView vector_ek441;
	private View _bg__group_ek81;
	private ImageView vector_ek442;
	private View _bg__group_ek83;
	private ImageView vector_ek443;
	private ImageView vector_ek444;
	private ImageView vector_ek445;
	private ImageView vector_ek446;
	private ImageView vector_ek447;
	private ImageView vector_ek448;
	private ImageView vector_ek449;
	private ImageView vector_ek450;
	private ImageView vector_ek451;
	private ImageView vector_ek452;
	private ImageView vector_ek453;
	private ImageView vector_ek454;
	private ImageView vector_ek455;
	private ImageView vector_ek456;
	private ImageView vector_ek457;
	private ImageView vector_ek458;
	private ImageView vector_ek459;
	private ImageView vector_ek460;
	private ImageView vector_ek461;
	private View _bg__group_ek85;
	private ImageView vector_ek462;
	private View _bg__group_ek87;
	private ImageView vector_ek463;
	private View _bg__group_ek89;
	private ImageView vector_ek464;
	private View _bg__group_ek91;
	private ImageView vector_ek465;
	private View _bg__group_ek93;
	private ImageView vector_ek466;
	private View _bg__group_ek95;
	private ImageView vector_ek467;
	private View _bg__group_ek97;
	private ImageView vector_ek468;
	private View _bg__freepik__microscope__inject_2_ek1;
	private View _bg__group_ek99;
	private ImageView vector_ek469;
	private ImageView vector_ek470;
	private ImageView vector_ek471;
	private ImageView vector_ek472;
	private ImageView vector_ek473;
	private ImageView vector_ek474;
	private ImageView vector_ek475;
	private ImageView vector_ek476;
	private ImageView vector_ek477;
	private ImageView vector_ek478;
	private ImageView vector_ek479;
	private ImageView vector_ek480;
	private ImageView vector_ek481;
	private ImageView vector_ek482;
	private ImageView vector_ek483;
	private ImageView vector_ek484;
	private ImageView vector_ek485;
	private ImageView vector_ek486;
	private ImageView vector_ek487;
	private ImageView vector_ek488;
	private ImageView vector_ek489;
	private ImageView vector_ek490;
	private ImageView vector_ek491;
	private ImageView vector_ek492;
	private ImageView vector_ek493;
	private ImageView vector_ek494;
	private ImageView vector_ek495;
	private ImageView vector_ek496;
	private ImageView vector_ek497;
	private View _bg__freepik__tubes_and_flasks__inject_2_ek1;
	private View _bg__group_ek101;
	private ImageView vector_ek498;
	private ImageView vector_ek499;
	private View _bg__group_ek103;
	private View _bg__group_ek105;
	private ImageView vector_ek500;
	private View _bg__group_ek107;
	private ImageView vector_ek501;
	private ImageView vector_ek502;
	private View _bg__group_ek109;
	private ImageView vector_ek503;
	private ImageView vector_ek504;
	private ImageView vector_ek505;
	private ImageView vector_ek506;
	private ImageView vector_ek507;
	private ImageView vector_ek508;
	private ImageView vector_ek509;
	private ImageView vector_ek510;
	private ImageView vector_ek511;
	private ImageView vector_ek512;
	private View _bg__group_ek111;
	private ImageView vector_ek513;
	private ImageView vector_ek514;
	private ImageView vector_ek515;
	private View _bg__group_ek113;
	private ImageView vector_ek516;
	private ImageView vector_ek517;
	private View _bg__group_ek115;
	private View _bg__group_ek117;
	private View _bg__group_ek119;
	private View _bg__group_ek121;
	private ImageView vector_ek518;
	private ImageView vector_ek519;
	private ImageView vector_ek520;
	private ImageView vector_ek521;
	private ImageView vector_ek522;
	private ImageView vector_ek523;
	private ImageView vector_ek524;
	private ImageView vector_ek525;
	private ImageView vector_ek526;
	private ImageView vector_ek527;
	private ImageView vector_ek528;
	private View _bg__group_ek123;
	private ImageView vector_ek529;
	private View _bg__group_ek125;
	private ImageView vector_ek530;
	private ImageView vector_ek531;
	private ImageView vector_ek532;
	private ImageView vector_ek533;
	private ImageView vector_ek534;
	private View _bg__group_ek127;
	private ImageView vector_ek535;
	private ImageView vector_ek536;
	private View _bg__group_ek129;
	private ImageView vector_ek537;
	private ImageView vector_ek538;
	private ImageView vector_ek539;
	private View _bg__group_ek131;
	private ImageView vector_ek540;
	private ImageView vector_ek541;
	private ImageView vector_ek542;
	private ImageView vector_ek543;
	private ImageView vector_ek544;
	private ImageView vector_ek545;
	private ImageView vector_ek546;
	private ImageView vector_ek547;
	private ImageView vector_ek548;
	private ImageView vector_ek549;
	private View _bg__group_ek133;
	private ImageView vector_ek550;
	private ImageView vector_ek551;
	private ImageView vector_ek552;
	private ImageView vector_ek553;
	private ImageView vector_ek554;
	private ImageView vector_ek555;
	private ImageView vector_ek556;
	private ImageView vector_ek557;
	private ImageView vector_ek558;
	private ImageView vector_ek559;
	private ImageView vector_ek560;
	private View _bg__group_ek135;
	private View _bg__group_ek137;
	private View _bg__group_ek139;
	private ImageView vector_ek561;
	private ImageView vector_ek562;
	private ImageView vector_ek563;
	private ImageView vector_ek564;
	private ImageView vector_ek565;
	private ImageView vector_ek566;
	private ImageView vector_ek567;
	private ImageView vector_ek568;
	private ImageView vector_ek569;
	private ImageView vector_ek570;
	private ImageView vector_ek571;
	private ImageView vector_ek572;
	private ImageView vector_ek573;
	private ImageView vector_ek574;
	private View _bg__group_ek141;
	private View _bg__group_ek143;
	private ImageView vector_ek575;
	private ImageView vector_ek576;
	private ImageView vector_ek577;
	private ImageView vector_ek578;
	private ImageView vector_ek579;
	private ImageView vector_ek580;
	private ImageView vector_ek581;
	private ImageView vector_ek582;
	private ImageView vector_ek583;
	private ImageView vector_ek584;
	private ImageView vector_ek585;
	private ImageView vector_ek586;
	private ImageView vector_ek587;
	private ImageView vector_ek588;
	private View _bg__group_ek145;
	private ImageView vector_ek589;
	private View _bg__group_ek147;
	private ImageView vector_ek590;
	private ImageView vector_ek591;
	private ImageView vector_ek592;
	private TextView tp;
	private ImageView x_1_ek5;
	private ImageView rectangle_32_ek6;
	private TextView academics_ek4;
	private TextView classroom;
	private TextView discover_ek7;
	private TextView profile_ek8;
	private View _bg__group_52_ek15;
	private ImageView vector_ek593;
	private ImageView vector_ek594;
	private ImageView vector_ek595;
	private ImageView vector_ek596;

	@Override
	public void onCreate(Bundle savedInstanceState) {

		super.onCreate(savedInstanceState);
		setContentView(R.layout.academics);

		
		_bg__academics_ek2 = (View) findViewById(R.id._bg__academics_ek2);
		academics_ek3 = (TextView) findViewById(R.id.academics_ek3);
		_bg__frame_103_ek1 = (View) findViewById(R.id._bg__frame_103_ek1);

		vector_ek108 = (ImageView) findViewById(R.id.vector_ek108);
		vector_ek109 = (ImageView) findViewById(R.id.vector_ek109);
		vector_ek110 = (ImageView) findViewById(R.id.vector_ek110);
		vector_ek111 = (ImageView) findViewById(R.id.vector_ek111);
		vector_ek112 = (ImageView) findViewById(R.id.vector_ek112);
		vector_ek113 = (ImageView) findViewById(R.id.vector_ek113);
		vector_ek114 = (ImageView) findViewById(R.id.vector_ek114);
		vector_ek115 = (ImageView) findViewById(R.id.vector_ek115);
		vector_ek116 = (ImageView) findViewById(R.id.vector_ek116);
		vector_ek117 = (ImageView) findViewById(R.id.vector_ek117);
		vector_ek118 = (ImageView) findViewById(R.id.vector_ek118);
		vector_ek119 = (ImageView) findViewById(R.id.vector_ek119);
		vector_ek120 = (ImageView) findViewById(R.id.vector_ek120);
		vector_ek121 = (ImageView) findViewById(R.id.vector_ek121);
		vector_ek122 = (ImageView) findViewById(R.id.vector_ek122);
		vector_ek123 = (ImageView) findViewById(R.id.vector_ek123);
		vector_ek124 = (ImageView) findViewById(R.id.vector_ek124);
		vector_ek125 = (ImageView) findViewById(R.id.vector_ek125);
		vector_ek126 = (ImageView) findViewById(R.id.vector_ek126);
		vector_ek127 = (ImageView) findViewById(R.id.vector_ek127);
		vector_ek128 = (ImageView) findViewById(R.id.vector_ek128);
		vector_ek129 = (ImageView) findViewById(R.id.vector_ek129);
		vector_ek130 = (ImageView) findViewById(R.id.vector_ek130);
		_bg__freepik__shadow__inject_2_ek1 = (View) findViewById(R.id._bg__freepik__shadow__inject_2_ek1);
		freepik__path__inject_2 = (ImageView) findViewById(R.id.freepik__path__inject_2);
		_bg__freepik__board__inject_2_ek1 = (View) findViewById(R.id._bg__freepik__board__inject_2_ek1);
		vector_ek131 = (ImageView) findViewById(R.id.vector_ek131);
		vector_ek132 = (ImageView) findViewById(R.id.vector_ek132);
		_bg__group_ek35 = (View) findViewById(R.id._bg__group_ek35);
		vector_ek133 = (ImageView) findViewById(R.id.vector_ek133);
		vector_ek134 = (ImageView) findViewById(R.id.vector_ek134);
		vector_ek135 = (ImageView) findViewById(R.id.vector_ek135);
		vector_ek136 = (ImageView) findViewById(R.id.vector_ek136);
		vector_ek137 = (ImageView) findViewById(R.id.vector_ek137);
		vector_ek138 = (ImageView) findViewById(R.id.vector_ek138);
		vector_ek139 = (ImageView) findViewById(R.id.vector_ek139);
		vector_ek140 = (ImageView) findViewById(R.id.vector_ek140);
		b = (TextView) findViewById(R.id.b);
		b_ek1 = (TextView) findViewById(R.id.b_ek1);
		c = (TextView) findViewById(R.id.c);
		c_ek1 = (TextView) findViewById(R.id.c_ek1);
		a = (TextView) findViewById(R.id.a);
		a_ek1 = (TextView) findViewById(R.id.a_ek1);
		vector_ek141 = (ImageView) findViewById(R.id.vector_ek141);
		vector_ek142 = (ImageView) findViewById(R.id.vector_ek142);
		vector_ek143 = (ImageView) findViewById(R.id.vector_ek143);
		vector_ek144 = (ImageView) findViewById(R.id.vector_ek144);
		vector_ek145 = (ImageView) findViewById(R.id.vector_ek145);
		vector_ek146 = (ImageView) findViewById(R.id.vector_ek146);
		vector_ek147 = (ImageView) findViewById(R.id.vector_ek147);
		vector_ek148 = (ImageView) findViewById(R.id.vector_ek148);
		vector_ek149 = (ImageView) findViewById(R.id.vector_ek149);
		vector_ek150 = (ImageView) findViewById(R.id.vector_ek150);
		vector_ek151 = (ImageView) findViewById(R.id.vector_ek151);
		vector_ek152 = (ImageView) findViewById(R.id.vector_ek152);
		vector_ek153 = (ImageView) findViewById(R.id.vector_ek153);
		vector_ek154 = (ImageView) findViewById(R.id.vector_ek154);
		vector_ek155 = (ImageView) findViewById(R.id.vector_ek155);
		vector_ek156 = (ImageView) findViewById(R.id.vector_ek156);
		vector_ek157 = (ImageView) findViewById(R.id.vector_ek157);
		vector_ek158 = (ImageView) findViewById(R.id.vector_ek158);
		vector_ek159 = (ImageView) findViewById(R.id.vector_ek159);
		vector_ek160 = (ImageView) findViewById(R.id.vector_ek160);
		vector_ek161 = (ImageView) findViewById(R.id.vector_ek161);
		vector_ek162 = (ImageView) findViewById(R.id.vector_ek162);
		vector_ek163 = (ImageView) findViewById(R.id.vector_ek163);
		vector_ek164 = (ImageView) findViewById(R.id.vector_ek164);
		vector_ek165 = (ImageView) findViewById(R.id.vector_ek165);
		vector_ek166 = (ImageView) findViewById(R.id.vector_ek166);
		vector_ek167 = (ImageView) findViewById(R.id.vector_ek167);
		_bg__freepik__teacher__inject_2_ek1 = (View) findViewById(R.id._bg__freepik__teacher__inject_2_ek1);
		vector_ek168 = (ImageView) findViewById(R.id.vector_ek168);
		vector_ek169 = (ImageView) findViewById(R.id.vector_ek169);
		vector_ek170 = (ImageView) findViewById(R.id.vector_ek170);
		vector_ek171 = (ImageView) findViewById(R.id.vector_ek171);
		vector_ek172 = (ImageView) findViewById(R.id.vector_ek172);
		vector_ek173 = (ImageView) findViewById(R.id.vector_ek173);
		vector_ek174 = (ImageView) findViewById(R.id.vector_ek174);
		vector_ek175 = (ImageView) findViewById(R.id.vector_ek175);
		vector_ek176 = (ImageView) findViewById(R.id.vector_ek176);
		vector_ek177 = (ImageView) findViewById(R.id.vector_ek177);
		vector_ek178 = (ImageView) findViewById(R.id.vector_ek178);
		vector_ek179 = (ImageView) findViewById(R.id.vector_ek179);
		vector_ek180 = (ImageView) findViewById(R.id.vector_ek180);
		vector_ek181 = (ImageView) findViewById(R.id.vector_ek181);
		vector_ek182 = (ImageView) findViewById(R.id.vector_ek182);
		vector_ek183 = (ImageView) findViewById(R.id.vector_ek183);
		vector_ek184 = (ImageView) findViewById(R.id.vector_ek184);
		vector_ek185 = (ImageView) findViewById(R.id.vector_ek185);
		vector_ek186 = (ImageView) findViewById(R.id.vector_ek186);
		vector_ek187 = (ImageView) findViewById(R.id.vector_ek187);
		vector_ek188 = (ImageView) findViewById(R.id.vector_ek188);
		vector_ek189 = (ImageView) findViewById(R.id.vector_ek189);
		vector_ek190 = (ImageView) findViewById(R.id.vector_ek190);
		vector_ek191 = (ImageView) findViewById(R.id.vector_ek191);
		vector_ek192 = (ImageView) findViewById(R.id.vector_ek192);
		vector_ek193 = (ImageView) findViewById(R.id.vector_ek193);
		vector_ek194 = (ImageView) findViewById(R.id.vector_ek194);
		vector_ek195 = (ImageView) findViewById(R.id.vector_ek195);
		vector_ek196 = (ImageView) findViewById(R.id.vector_ek196);
		vector_ek197 = (ImageView) findViewById(R.id.vector_ek197);
		vector_ek198 = (ImageView) findViewById(R.id.vector_ek198);
		vector_ek199 = (ImageView) findViewById(R.id.vector_ek199);
		vector_ek200 = (ImageView) findViewById(R.id.vector_ek200);
		vector_ek201 = (ImageView) findViewById(R.id.vector_ek201);
		vector_ek202 = (ImageView) findViewById(R.id.vector_ek202);
		vector_ek203 = (ImageView) findViewById(R.id.vector_ek203);
		vector_ek204 = (ImageView) findViewById(R.id.vector_ek204);
		vector_ek205 = (ImageView) findViewById(R.id.vector_ek205);
		vector_ek206 = (ImageView) findViewById(R.id.vector_ek206);
		vector_ek207 = (ImageView) findViewById(R.id.vector_ek207);
		vector_ek208 = (ImageView) findViewById(R.id.vector_ek208);
		vector_ek209 = (ImageView) findViewById(R.id.vector_ek209);
		vector_ek210 = (ImageView) findViewById(R.id.vector_ek210);
		vector_ek211 = (ImageView) findViewById(R.id.vector_ek211);
		vector_ek212 = (ImageView) findViewById(R.id.vector_ek212);
		vector_ek213 = (ImageView) findViewById(R.id.vector_ek213);
		vector_ek214 = (ImageView) findViewById(R.id.vector_ek214);
		_bg__freepik__table__inject_2_ek1 = (View) findViewById(R.id._bg__freepik__table__inject_2_ek1);
		vector_ek215 = (ImageView) findViewById(R.id.vector_ek215);
		vector_ek216 = (ImageView) findViewById(R.id.vector_ek216);
		vector_ek217 = (ImageView) findViewById(R.id.vector_ek217);
		vector_ek218 = (ImageView) findViewById(R.id.vector_ek218);
		vector_ek219 = (ImageView) findViewById(R.id.vector_ek219);
		vector_ek220 = (ImageView) findViewById(R.id.vector_ek220);
		vector_ek221 = (ImageView) findViewById(R.id.vector_ek221);
		vector_ek222 = (ImageView) findViewById(R.id.vector_ek222);
		vector_ek223 = (ImageView) findViewById(R.id.vector_ek223);
		vector_ek224 = (ImageView) findViewById(R.id.vector_ek224);
		vector_ek225 = (ImageView) findViewById(R.id.vector_ek225);
		vector_ek226 = (ImageView) findViewById(R.id.vector_ek226);
		vector_ek227 = (ImageView) findViewById(R.id.vector_ek227);
		vector_ek228 = (ImageView) findViewById(R.id.vector_ek228);
		vector_ek229 = (ImageView) findViewById(R.id.vector_ek229);
		vector_ek230 = (ImageView) findViewById(R.id.vector_ek230);
		vector_ek231 = (ImageView) findViewById(R.id.vector_ek231);
		vector_ek232 = (ImageView) findViewById(R.id.vector_ek232);
		vector_ek233 = (ImageView) findViewById(R.id.vector_ek233);
		_bg__freepik__student__inject_2_ek1 = (View) findViewById(R.id._bg__freepik__student__inject_2_ek1);
		_bg__freepik__group__inject_2_ek1 = (View) findViewById(R.id._bg__freepik__group__inject_2_ek1);
		vector_ek234 = (ImageView) findViewById(R.id.vector_ek234);
		vector_ek235 = (ImageView) findViewById(R.id.vector_ek235);
		vector_ek236 = (ImageView) findViewById(R.id.vector_ek236);
		vector_ek237 = (ImageView) findViewById(R.id.vector_ek237);
		vector_ek238 = (ImageView) findViewById(R.id.vector_ek238);
		vector_ek239 = (ImageView) findViewById(R.id.vector_ek239);
		vector_ek240 = (ImageView) findViewById(R.id.vector_ek240);
		vector_ek241 = (ImageView) findViewById(R.id.vector_ek241);
		vector_ek242 = (ImageView) findViewById(R.id.vector_ek242);
		vector_ek243 = (ImageView) findViewById(R.id.vector_ek243);
		vector_ek244 = (ImageView) findViewById(R.id.vector_ek244);
		vector_ek245 = (ImageView) findViewById(R.id.vector_ek245);
		vector_ek246 = (ImageView) findViewById(R.id.vector_ek246);
		vector_ek247 = (ImageView) findViewById(R.id.vector_ek247);
		vector_ek248 = (ImageView) findViewById(R.id.vector_ek248);
		vector_ek249 = (ImageView) findViewById(R.id.vector_ek249);
		vector_ek250 = (ImageView) findViewById(R.id.vector_ek250);
		vector_ek251 = (ImageView) findViewById(R.id.vector_ek251);
		vector_ek252 = (ImageView) findViewById(R.id.vector_ek252);
		vector_ek253 = (ImageView) findViewById(R.id.vector_ek253);
		vector_ek254 = (ImageView) findViewById(R.id.vector_ek254);
		vector_ek255 = (ImageView) findViewById(R.id.vector_ek255);
		vector_ek256 = (ImageView) findViewById(R.id.vector_ek256);
		vector_ek257 = (ImageView) findViewById(R.id.vector_ek257);
		vector_ek258 = (ImageView) findViewById(R.id.vector_ek258);
		vector_ek259 = (ImageView) findViewById(R.id.vector_ek259);
		vector_ek260 = (ImageView) findViewById(R.id.vector_ek260);
		vector_ek261 = (ImageView) findViewById(R.id.vector_ek261);
		vector_ek262 = (ImageView) findViewById(R.id.vector_ek262);
		_bg__freepik__chair__inject_2_ek1 = (View) findViewById(R.id._bg__freepik__chair__inject_2_ek1);
		vector_ek263 = (ImageView) findViewById(R.id.vector_ek263);
		vector_ek264 = (ImageView) findViewById(R.id.vector_ek264);
		vector_ek265 = (ImageView) findViewById(R.id.vector_ek265);
		vector_ek266 = (ImageView) findViewById(R.id.vector_ek266);
		vector_ek267 = (ImageView) findViewById(R.id.vector_ek267);
		vector_ek268 = (ImageView) findViewById(R.id.vector_ek268);
		vector_ek269 = (ImageView) findViewById(R.id.vector_ek269);
		vector_ek270 = (ImageView) findViewById(R.id.vector_ek270);
		vector_ek271 = (ImageView) findViewById(R.id.vector_ek271);
		vector_ek272 = (ImageView) findViewById(R.id.vector_ek272);
		vector_ek273 = (ImageView) findViewById(R.id.vector_ek273);
		vector_ek274 = (ImageView) findViewById(R.id.vector_ek274);
		_bg__group_ek37 = (View) findViewById(R.id._bg__group_ek37);
		vector_ek275 = (ImageView) findViewById(R.id.vector_ek275);
		_bg__group_ek39 = (View) findViewById(R.id._bg__group_ek39);
		vector_ek276 = (ImageView) findViewById(R.id.vector_ek276);
		vector_ek277 = (ImageView) findViewById(R.id.vector_ek277);
		vector_ek278 = (ImageView) findViewById(R.id.vector_ek278);
		vector_ek279 = (ImageView) findViewById(R.id.vector_ek279);
		vector_ek280 = (ImageView) findViewById(R.id.vector_ek280);
		courses_ek13 = (TextView) findViewById(R.id.courses_ek13);
		_bg__frame_105_ek1 = (View) findViewById(R.id._bg__frame_105_ek1);
		vector_ek281 = (ImageView) findViewById(R.id.vector_ek281);
		vector_ek282 = (ImageView) findViewById(R.id.vector_ek282);
		vector_ek283 = (ImageView) findViewById(R.id.vector_ek283);
		vector_ek284 = (ImageView) findViewById(R.id.vector_ek284);
		vector_ek285 = (ImageView) findViewById(R.id.vector_ek285);
		vector_ek286 = (ImageView) findViewById(R.id.vector_ek286);
		vector_ek287 = (ImageView) findViewById(R.id.vector_ek287);
		vector_ek288 = (ImageView) findViewById(R.id.vector_ek288);
		vector_ek289 = (ImageView) findViewById(R.id.vector_ek289);
		vector_ek290 = (ImageView) findViewById(R.id.vector_ek290);
		vector_ek291 = (ImageView) findViewById(R.id.vector_ek291);
		vector_ek292 = (ImageView) findViewById(R.id.vector_ek292);
		vector_ek293 = (ImageView) findViewById(R.id.vector_ek293);
		vector_ek294 = (ImageView) findViewById(R.id.vector_ek294);
		vector_ek295 = (ImageView) findViewById(R.id.vector_ek295);
		vector_ek296 = (ImageView) findViewById(R.id.vector_ek296);
		vector_ek297 = (ImageView) findViewById(R.id.vector_ek297);
		vector_ek298 = (ImageView) findViewById(R.id.vector_ek298);
		vector_ek299 = (ImageView) findViewById(R.id.vector_ek299);
		vector_ek300 = (ImageView) findViewById(R.id.vector_ek300);
		vector_ek301 = (ImageView) findViewById(R.id.vector_ek301);
		vector_ek302 = (ImageView) findViewById(R.id.vector_ek302);
		vector_ek303 = (ImageView) findViewById(R.id.vector_ek303);
		vector_ek304 = (ImageView) findViewById(R.id.vector_ek304);
		vector_ek305 = (ImageView) findViewById(R.id.vector_ek305);
		vector_ek306 = (ImageView) findViewById(R.id.vector_ek306);
		vector_ek307 = (ImageView) findViewById(R.id.vector_ek307);
		vector_ek308 = (ImageView) findViewById(R.id.vector_ek308);
		vector_ek309 = (ImageView) findViewById(R.id.vector_ek309);
		vector_ek310 = (ImageView) findViewById(R.id.vector_ek310);
		vector_ek311 = (ImageView) findViewById(R.id.vector_ek311);
		vector_ek312 = (ImageView) findViewById(R.id.vector_ek312);
		vector_ek313 = (ImageView) findViewById(R.id.vector_ek313);
		vector_ek314 = (ImageView) findViewById(R.id.vector_ek314);
		vector_ek315 = (ImageView) findViewById(R.id.vector_ek315);
		vector_ek316 = (ImageView) findViewById(R.id.vector_ek316);
		vector_ek317 = (ImageView) findViewById(R.id.vector_ek317);
		vector_ek318 = (ImageView) findViewById(R.id.vector_ek318);
		vector_ek319 = (ImageView) findViewById(R.id.vector_ek319);
		vector_ek320 = (ImageView) findViewById(R.id.vector_ek320);
		vector_ek321 = (ImageView) findViewById(R.id.vector_ek321);
		vector_ek322 = (ImageView) findViewById(R.id.vector_ek322);
		vector_ek323 = (ImageView) findViewById(R.id.vector_ek323);
		vector_ek324 = (ImageView) findViewById(R.id.vector_ek324);
		vector_ek325 = (ImageView) findViewById(R.id.vector_ek325);
		vector_ek326 = (ImageView) findViewById(R.id.vector_ek326);
		vector_ek327 = (ImageView) findViewById(R.id.vector_ek327);
		_bg__freepik__shadow__inject_15_ek1 = (View) findViewById(R.id._bg__freepik__shadow__inject_15_ek1);
		freepik__path__inject_15 = (ImageView) findViewById(R.id.freepik__path__inject_15);
		_bg__freepik__survey__inject_15_ek1 = (View) findViewById(R.id._bg__freepik__survey__inject_15_ek1);
		vector_ek328 = (ImageView) findViewById(R.id.vector_ek328);
		vector_ek329 = (ImageView) findViewById(R.id.vector_ek329);
		vector_ek330 = (ImageView) findViewById(R.id.vector_ek330);
		vector_ek331 = (ImageView) findViewById(R.id.vector_ek331);
		_bg__group_ek41 = (View) findViewById(R.id._bg__group_ek41);
		vector_ek332 = (ImageView) findViewById(R.id.vector_ek332);
		vector_ek333 = (ImageView) findViewById(R.id.vector_ek333);
		vector_ek334 = (ImageView) findViewById(R.id.vector_ek334);
		_bg__group_ek43 = (View) findViewById(R.id._bg__group_ek43);
		vector_ek335 = (ImageView) findViewById(R.id.vector_ek335);
		vector_ek336 = (ImageView) findViewById(R.id.vector_ek336);
		vector_ek337 = (ImageView) findViewById(R.id.vector_ek337);
		vector_ek338 = (ImageView) findViewById(R.id.vector_ek338);
		_bg__group_ek45 = (View) findViewById(R.id._bg__group_ek45);
		vector_ek339 = (ImageView) findViewById(R.id.vector_ek339);
		vector_ek340 = (ImageView) findViewById(R.id.vector_ek340);
		vector_ek341 = (ImageView) findViewById(R.id.vector_ek341);
		vector_ek342 = (ImageView) findViewById(R.id.vector_ek342);
		vector_ek343 = (ImageView) findViewById(R.id.vector_ek343);
		vector_ek344 = (ImageView) findViewById(R.id.vector_ek344);
		vector_ek345 = (ImageView) findViewById(R.id.vector_ek345);
		vector_ek346 = (ImageView) findViewById(R.id.vector_ek346);
		vector_ek347 = (ImageView) findViewById(R.id.vector_ek347);
		vector_ek348 = (ImageView) findViewById(R.id.vector_ek348);
		vector_ek349 = (ImageView) findViewById(R.id.vector_ek349);
		vector_ek350 = (ImageView) findViewById(R.id.vector_ek350);
		vector_ek351 = (ImageView) findViewById(R.id.vector_ek351);
		vector_ek352 = (ImageView) findViewById(R.id.vector_ek352);
		vector_ek353 = (ImageView) findViewById(R.id.vector_ek353);
		vector_ek354 = (ImageView) findViewById(R.id.vector_ek354);
		vector_ek355 = (ImageView) findViewById(R.id.vector_ek355);
		vector_ek356 = (ImageView) findViewById(R.id.vector_ek356);
		vector_ek357 = (ImageView) findViewById(R.id.vector_ek357);
		vector_ek358 = (ImageView) findViewById(R.id.vector_ek358);
		vector_ek359 = (ImageView) findViewById(R.id.vector_ek359);
		vector_ek360 = (ImageView) findViewById(R.id.vector_ek360);
		vector_ek361 = (ImageView) findViewById(R.id.vector_ek361);
		vector_ek362 = (ImageView) findViewById(R.id.vector_ek362);
		_bg__freepik__character__inject_15_ek1 = (View) findViewById(R.id._bg__freepik__character__inject_15_ek1);
		vector_ek363 = (ImageView) findViewById(R.id.vector_ek363);
		vector_ek364 = (ImageView) findViewById(R.id.vector_ek364);
		vector_ek365 = (ImageView) findViewById(R.id.vector_ek365);
		vector_ek366 = (ImageView) findViewById(R.id.vector_ek366);
		vector_ek367 = (ImageView) findViewById(R.id.vector_ek367);
		vector_ek368 = (ImageView) findViewById(R.id.vector_ek368);
		vector_ek369 = (ImageView) findViewById(R.id.vector_ek369);
		vector_ek370 = (ImageView) findViewById(R.id.vector_ek370);
		vector_ek371 = (ImageView) findViewById(R.id.vector_ek371);
		vector_ek372 = (ImageView) findViewById(R.id.vector_ek372);
		vector_ek373 = (ImageView) findViewById(R.id.vector_ek373);
		vector_ek374 = (ImageView) findViewById(R.id.vector_ek374);
		vector_ek375 = (ImageView) findViewById(R.id.vector_ek375);
		vector_ek376 = (ImageView) findViewById(R.id.vector_ek376);
		vector_ek377 = (ImageView) findViewById(R.id.vector_ek377);
		vector_ek378 = (ImageView) findViewById(R.id.vector_ek378);
		vector_ek379 = (ImageView) findViewById(R.id.vector_ek379);
		vector_ek380 = (ImageView) findViewById(R.id.vector_ek380);
		vector_ek381 = (ImageView) findViewById(R.id.vector_ek381);
		vector_ek382 = (ImageView) findViewById(R.id.vector_ek382);
		vector_ek383 = (ImageView) findViewById(R.id.vector_ek383);
		vector_ek384 = (ImageView) findViewById(R.id.vector_ek384);
		vector_ek385 = (ImageView) findViewById(R.id.vector_ek385);
		vector_ek386 = (ImageView) findViewById(R.id.vector_ek386);
		vector_ek387 = (ImageView) findViewById(R.id.vector_ek387);
		vector_ek388 = (ImageView) findViewById(R.id.vector_ek388);
		vector_ek389 = (ImageView) findViewById(R.id.vector_ek389);
		vector_ek390 = (ImageView) findViewById(R.id.vector_ek390);
		vector_ek391 = (ImageView) findViewById(R.id.vector_ek391);
		vector_ek392 = (ImageView) findViewById(R.id.vector_ek392);
		vector_ek393 = (ImageView) findViewById(R.id.vector_ek393);
		vector_ek394 = (ImageView) findViewById(R.id.vector_ek394);
		vector_ek395 = (ImageView) findViewById(R.id.vector_ek395);
		vector_ek396 = (ImageView) findViewById(R.id.vector_ek396);
		vector_ek397 = (ImageView) findViewById(R.id.vector_ek397);
		quizzes_ek10 = (TextView) findViewById(R.id.quizzes_ek10);
		_bg__frame_104_ek1 = (View) findViewById(R.id._bg__frame_104_ek1);


		vector_ek398 = (ImageView) findViewById(R.id.vector_ek398);
		vector_ek399 = (ImageView) findViewById(R.id.vector_ek399);
		vector_ek400 = (ImageView) findViewById(R.id.vector_ek400);
		vector_ek401 = (ImageView) findViewById(R.id.vector_ek401);
		vector_ek402 = (ImageView) findViewById(R.id.vector_ek402);
		vector_ek403 = (ImageView) findViewById(R.id.vector_ek403);
		vector_ek404 = (ImageView) findViewById(R.id.vector_ek404);
		vector_ek405 = (ImageView) findViewById(R.id.vector_ek405);
		vector_ek406 = (ImageView) findViewById(R.id.vector_ek406);
		vector_ek407 = (ImageView) findViewById(R.id.vector_ek407);
		vector_ek408 = (ImageView) findViewById(R.id.vector_ek408);
		vector_ek409 = (ImageView) findViewById(R.id.vector_ek409);
		vector_ek410 = (ImageView) findViewById(R.id.vector_ek410);
		_bg__group_ek53 = (View) findViewById(R.id._bg__group_ek53);
		vector_ek411 = (ImageView) findViewById(R.id.vector_ek411);
		vector_ek412 = (ImageView) findViewById(R.id.vector_ek412);
		_bg__group_ek55 = (View) findViewById(R.id._bg__group_ek55);
		vector_ek413 = (ImageView) findViewById(R.id.vector_ek413);
		vector_ek414 = (ImageView) findViewById(R.id.vector_ek414);
		_bg__group_ek57 = (View) findViewById(R.id._bg__group_ek57);
		vector_ek415 = (ImageView) findViewById(R.id.vector_ek415);
		vector_ek416 = (ImageView) findViewById(R.id.vector_ek416);
		_bg__group_ek59 = (View) findViewById(R.id._bg__group_ek59);
		vector_ek417 = (ImageView) findViewById(R.id.vector_ek417);
		vector_ek418 = (ImageView) findViewById(R.id.vector_ek418);
		_bg__group_ek61 = (View) findViewById(R.id._bg__group_ek61);
		_bg__group_ek63 = (View) findViewById(R.id._bg__group_ek63);
		vector_ek419 = (ImageView) findViewById(R.id.vector_ek419);
		vector_ek420 = (ImageView) findViewById(R.id.vector_ek420);
		vector_ek421 = (ImageView) findViewById(R.id.vector_ek421);
		_bg__group_ek65 = (View) findViewById(R.id._bg__group_ek65);
		_bg__group_ek67 = (View) findViewById(R.id._bg__group_ek67);
		vector_ek422 = (ImageView) findViewById(R.id.vector_ek422);
		_bg__group_ek69 = (View) findViewById(R.id._bg__group_ek69);
		vector_ek423 = (ImageView) findViewById(R.id.vector_ek423);
		vector_ek424 = (ImageView) findViewById(R.id.vector_ek424);
		vector_ek425 = (ImageView) findViewById(R.id.vector_ek425);
		vector_ek426 = (ImageView) findViewById(R.id.vector_ek426);
		vector_ek427 = (ImageView) findViewById(R.id.vector_ek427);
		vector_ek428 = (ImageView) findViewById(R.id.vector_ek428);
		vector_ek429 = (ImageView) findViewById(R.id.vector_ek429);
		_bg__group_ek71 = (View) findViewById(R.id._bg__group_ek71);
		vector_ek430 = (ImageView) findViewById(R.id.vector_ek430);
		vector_ek431 = (ImageView) findViewById(R.id.vector_ek431);
		_bg__group_ek73 = (View) findViewById(R.id._bg__group_ek73);
		_bg__group_ek75 = (View) findViewById(R.id._bg__group_ek75);
		vector_ek432 = (ImageView) findViewById(R.id.vector_ek432);
		_bg__group_ek77 = (View) findViewById(R.id._bg__group_ek77);
		vector_ek433 = (ImageView) findViewById(R.id.vector_ek433);
		vector_ek434 = (ImageView) findViewById(R.id.vector_ek434);
		vector_ek435 = (ImageView) findViewById(R.id.vector_ek435);
		vector_ek436 = (ImageView) findViewById(R.id.vector_ek436);
		vector_ek437 = (ImageView) findViewById(R.id.vector_ek437);
		vector_ek438 = (ImageView) findViewById(R.id.vector_ek438);
		vector_ek439 = (ImageView) findViewById(R.id.vector_ek439);
		_bg__freepik__shadow__inject_2_ek3 = (View) findViewById(R.id._bg__freepik__shadow__inject_2_ek3);
		vector_ek440 = (ImageView) findViewById(R.id.vector_ek440);
		_bg__freepik__picture__inject_2_ek1 = (View) findViewById(R.id._bg__freepik__picture__inject_2_ek1);
		_bg__group_ek79 = (View) findViewById(R.id._bg__group_ek79);
		vector_ek441 = (ImageView) findViewById(R.id.vector_ek441);
		_bg__group_ek81 = (View) findViewById(R.id._bg__group_ek81);
		vector_ek442 = (ImageView) findViewById(R.id.vector_ek442);
		_bg__group_ek83 = (View) findViewById(R.id._bg__group_ek83);
		vector_ek443 = (ImageView) findViewById(R.id.vector_ek443);
		vector_ek444 = (ImageView) findViewById(R.id.vector_ek444);
		vector_ek445 = (ImageView) findViewById(R.id.vector_ek445);
		vector_ek446 = (ImageView) findViewById(R.id.vector_ek446);
		vector_ek447 = (ImageView) findViewById(R.id.vector_ek447);
		vector_ek448 = (ImageView) findViewById(R.id.vector_ek448);
		vector_ek449 = (ImageView) findViewById(R.id.vector_ek449);
		vector_ek450 = (ImageView) findViewById(R.id.vector_ek450);
		vector_ek451 = (ImageView) findViewById(R.id.vector_ek451);
		vector_ek452 = (ImageView) findViewById(R.id.vector_ek452);
		vector_ek453 = (ImageView) findViewById(R.id.vector_ek453);
		vector_ek454 = (ImageView) findViewById(R.id.vector_ek454);
		vector_ek455 = (ImageView) findViewById(R.id.vector_ek455);
		vector_ek456 = (ImageView) findViewById(R.id.vector_ek456);
		vector_ek457 = (ImageView) findViewById(R.id.vector_ek457);
		vector_ek458 = (ImageView) findViewById(R.id.vector_ek458);
		vector_ek459 = (ImageView) findViewById(R.id.vector_ek459);
		vector_ek460 = (ImageView) findViewById(R.id.vector_ek460);
		vector_ek461 = (ImageView) findViewById(R.id.vector_ek461);
		_bg__group_ek85 = (View) findViewById(R.id._bg__group_ek85);
		vector_ek462 = (ImageView) findViewById(R.id.vector_ek462);
		_bg__group_ek87 = (View) findViewById(R.id._bg__group_ek87);
		vector_ek463 = (ImageView) findViewById(R.id.vector_ek463);
		_bg__group_ek89 = (View) findViewById(R.id._bg__group_ek89);
		vector_ek464 = (ImageView) findViewById(R.id.vector_ek464);
		_bg__group_ek91 = (View) findViewById(R.id._bg__group_ek91);
		vector_ek465 = (ImageView) findViewById(R.id.vector_ek465);
		_bg__group_ek93 = (View) findViewById(R.id._bg__group_ek93);
		vector_ek466 = (ImageView) findViewById(R.id.vector_ek466);
		_bg__group_ek95 = (View) findViewById(R.id._bg__group_ek95);
		vector_ek467 = (ImageView) findViewById(R.id.vector_ek467);
		_bg__group_ek97 = (View) findViewById(R.id._bg__group_ek97);
		vector_ek468 = (ImageView) findViewById(R.id.vector_ek468);
		_bg__freepik__microscope__inject_2_ek1 = (View) findViewById(R.id._bg__freepik__microscope__inject_2_ek1);
		_bg__group_ek99 = (View) findViewById(R.id._bg__group_ek99);
		vector_ek469 = (ImageView) findViewById(R.id.vector_ek469);
		vector_ek470 = (ImageView) findViewById(R.id.vector_ek470);
		vector_ek471 = (ImageView) findViewById(R.id.vector_ek471);
		vector_ek472 = (ImageView) findViewById(R.id.vector_ek472);
		vector_ek473 = (ImageView) findViewById(R.id.vector_ek473);
		vector_ek474 = (ImageView) findViewById(R.id.vector_ek474);
		vector_ek475 = (ImageView) findViewById(R.id.vector_ek475);
		vector_ek476 = (ImageView) findViewById(R.id.vector_ek476);
		vector_ek477 = (ImageView) findViewById(R.id.vector_ek477);
		vector_ek478 = (ImageView) findViewById(R.id.vector_ek478);
		vector_ek479 = (ImageView) findViewById(R.id.vector_ek479);
		vector_ek480 = (ImageView) findViewById(R.id.vector_ek480);
		vector_ek481 = (ImageView) findViewById(R.id.vector_ek481);
		vector_ek482 = (ImageView) findViewById(R.id.vector_ek482);
		vector_ek483 = (ImageView) findViewById(R.id.vector_ek483);
		vector_ek484 = (ImageView) findViewById(R.id.vector_ek484);
		vector_ek485 = (ImageView) findViewById(R.id.vector_ek485);
		vector_ek486 = (ImageView) findViewById(R.id.vector_ek486);
		vector_ek487 = (ImageView) findViewById(R.id.vector_ek487);
		vector_ek488 = (ImageView) findViewById(R.id.vector_ek488);
		vector_ek489 = (ImageView) findViewById(R.id.vector_ek489);
		vector_ek490 = (ImageView) findViewById(R.id.vector_ek490);
		vector_ek491 = (ImageView) findViewById(R.id.vector_ek491);
		vector_ek492 = (ImageView) findViewById(R.id.vector_ek492);
		vector_ek493 = (ImageView) findViewById(R.id.vector_ek493);
		vector_ek494 = (ImageView) findViewById(R.id.vector_ek494);
		vector_ek495 = (ImageView) findViewById(R.id.vector_ek495);
		vector_ek496 = (ImageView) findViewById(R.id.vector_ek496);
		vector_ek497 = (ImageView) findViewById(R.id.vector_ek497);
		_bg__freepik__tubes_and_flasks__inject_2_ek1 = (View) findViewById(R.id._bg__freepik__tubes_and_flasks__inject_2_ek1);
		_bg__group_ek101 = (View) findViewById(R.id._bg__group_ek101);
		vector_ek498 = (ImageView) findViewById(R.id.vector_ek498);
		vector_ek499 = (ImageView) findViewById(R.id.vector_ek499);
		_bg__group_ek103 = (View) findViewById(R.id._bg__group_ek103);
		_bg__group_ek105 = (View) findViewById(R.id._bg__group_ek105);
		vector_ek500 = (ImageView) findViewById(R.id.vector_ek500);
		_bg__group_ek107 = (View) findViewById(R.id._bg__group_ek107);
		vector_ek501 = (ImageView) findViewById(R.id.vector_ek501);
		vector_ek502 = (ImageView) findViewById(R.id.vector_ek502);
		_bg__group_ek109 = (View) findViewById(R.id._bg__group_ek109);
		vector_ek503 = (ImageView) findViewById(R.id.vector_ek503);
		vector_ek504 = (ImageView) findViewById(R.id.vector_ek504);
		vector_ek505 = (ImageView) findViewById(R.id.vector_ek505);
		vector_ek506 = (ImageView) findViewById(R.id.vector_ek506);
		vector_ek507 = (ImageView) findViewById(R.id.vector_ek507);
		vector_ek508 = (ImageView) findViewById(R.id.vector_ek508);
		vector_ek509 = (ImageView) findViewById(R.id.vector_ek509);
		vector_ek510 = (ImageView) findViewById(R.id.vector_ek510);
		vector_ek511 = (ImageView) findViewById(R.id.vector_ek511);
		vector_ek512 = (ImageView) findViewById(R.id.vector_ek512);
		_bg__group_ek111 = (View) findViewById(R.id._bg__group_ek111);
		vector_ek513 = (ImageView) findViewById(R.id.vector_ek513);
		vector_ek514 = (ImageView) findViewById(R.id.vector_ek514);
		vector_ek515 = (ImageView) findViewById(R.id.vector_ek515);
		_bg__group_ek113 = (View) findViewById(R.id._bg__group_ek113);
		vector_ek516 = (ImageView) findViewById(R.id.vector_ek516);
		vector_ek517 = (ImageView) findViewById(R.id.vector_ek517);
		_bg__group_ek115 = (View) findViewById(R.id._bg__group_ek115);
		_bg__group_ek117 = (View) findViewById(R.id._bg__group_ek117);
		_bg__group_ek119 = (View) findViewById(R.id._bg__group_ek119);
		_bg__group_ek121 = (View) findViewById(R.id._bg__group_ek121);
		vector_ek518 = (ImageView) findViewById(R.id.vector_ek518);
		vector_ek519 = (ImageView) findViewById(R.id.vector_ek519);
		vector_ek520 = (ImageView) findViewById(R.id.vector_ek520);
		vector_ek521 = (ImageView) findViewById(R.id.vector_ek521);
		vector_ek522 = (ImageView) findViewById(R.id.vector_ek522);
		vector_ek523 = (ImageView) findViewById(R.id.vector_ek523);
		vector_ek524 = (ImageView) findViewById(R.id.vector_ek524);
		vector_ek525 = (ImageView) findViewById(R.id.vector_ek525);
		vector_ek526 = (ImageView) findViewById(R.id.vector_ek526);
		vector_ek527 = (ImageView) findViewById(R.id.vector_ek527);
		vector_ek528 = (ImageView) findViewById(R.id.vector_ek528);
		_bg__group_ek123 = (View) findViewById(R.id._bg__group_ek123);
		vector_ek529 = (ImageView) findViewById(R.id.vector_ek529);
		_bg__group_ek125 = (View) findViewById(R.id._bg__group_ek125);
		vector_ek530 = (ImageView) findViewById(R.id.vector_ek530);
		vector_ek531 = (ImageView) findViewById(R.id.vector_ek531);
		vector_ek532 = (ImageView) findViewById(R.id.vector_ek532);
		vector_ek533 = (ImageView) findViewById(R.id.vector_ek533);
		vector_ek534 = (ImageView) findViewById(R.id.vector_ek534);
		_bg__group_ek127 = (View) findViewById(R.id._bg__group_ek127);
		vector_ek535 = (ImageView) findViewById(R.id.vector_ek535);
		vector_ek536 = (ImageView) findViewById(R.id.vector_ek536);
		_bg__group_ek129 = (View) findViewById(R.id._bg__group_ek129);
		vector_ek537 = (ImageView) findViewById(R.id.vector_ek537);
		vector_ek538 = (ImageView) findViewById(R.id.vector_ek538);
		vector_ek539 = (ImageView) findViewById(R.id.vector_ek539);
		_bg__group_ek131 = (View) findViewById(R.id._bg__group_ek131);
		vector_ek540 = (ImageView) findViewById(R.id.vector_ek540);
		vector_ek541 = (ImageView) findViewById(R.id.vector_ek541);
		vector_ek542 = (ImageView) findViewById(R.id.vector_ek542);
		vector_ek543 = (ImageView) findViewById(R.id.vector_ek543);
		vector_ek544 = (ImageView) findViewById(R.id.vector_ek544);
		vector_ek545 = (ImageView) findViewById(R.id.vector_ek545);
		vector_ek546 = (ImageView) findViewById(R.id.vector_ek546);
		vector_ek547 = (ImageView) findViewById(R.id.vector_ek547);
		vector_ek548 = (ImageView) findViewById(R.id.vector_ek548);
		vector_ek549 = (ImageView) findViewById(R.id.vector_ek549);
		_bg__group_ek133 = (View) findViewById(R.id._bg__group_ek133);
		vector_ek550 = (ImageView) findViewById(R.id.vector_ek550);
		vector_ek551 = (ImageView) findViewById(R.id.vector_ek551);
		vector_ek552 = (ImageView) findViewById(R.id.vector_ek552);
		vector_ek553 = (ImageView) findViewById(R.id.vector_ek553);
		vector_ek554 = (ImageView) findViewById(R.id.vector_ek554);
		vector_ek555 = (ImageView) findViewById(R.id.vector_ek555);
		vector_ek556 = (ImageView) findViewById(R.id.vector_ek556);
		vector_ek557 = (ImageView) findViewById(R.id.vector_ek557);
		vector_ek558 = (ImageView) findViewById(R.id.vector_ek558);
		vector_ek559 = (ImageView) findViewById(R.id.vector_ek559);
		vector_ek560 = (ImageView) findViewById(R.id.vector_ek560);
		_bg__group_ek135 = (View) findViewById(R.id._bg__group_ek135);
		_bg__group_ek137 = (View) findViewById(R.id._bg__group_ek137);
		_bg__group_ek139 = (View) findViewById(R.id._bg__group_ek139);
		vector_ek561 = (ImageView) findViewById(R.id.vector_ek561);
		vector_ek562 = (ImageView) findViewById(R.id.vector_ek562);
		vector_ek563 = (ImageView) findViewById(R.id.vector_ek563);
		vector_ek564 = (ImageView) findViewById(R.id.vector_ek564);
		vector_ek565 = (ImageView) findViewById(R.id.vector_ek565);
		vector_ek566 = (ImageView) findViewById(R.id.vector_ek566);
		vector_ek567 = (ImageView) findViewById(R.id.vector_ek567);
		vector_ek568 = (ImageView) findViewById(R.id.vector_ek568);
		vector_ek569 = (ImageView) findViewById(R.id.vector_ek569);
		vector_ek570 = (ImageView) findViewById(R.id.vector_ek570);
		vector_ek571 = (ImageView) findViewById(R.id.vector_ek571);
		vector_ek572 = (ImageView) findViewById(R.id.vector_ek572);
		vector_ek573 = (ImageView) findViewById(R.id.vector_ek573);
		vector_ek574 = (ImageView) findViewById(R.id.vector_ek574);
		_bg__group_ek141 = (View) findViewById(R.id._bg__group_ek141);
		_bg__group_ek143 = (View) findViewById(R.id._bg__group_ek143);
		vector_ek575 = (ImageView) findViewById(R.id.vector_ek575);
		vector_ek576 = (ImageView) findViewById(R.id.vector_ek576);
		vector_ek577 = (ImageView) findViewById(R.id.vector_ek577);
		vector_ek578 = (ImageView) findViewById(R.id.vector_ek578);
		vector_ek579 = (ImageView) findViewById(R.id.vector_ek579);
		vector_ek580 = (ImageView) findViewById(R.id.vector_ek580);
		vector_ek581 = (ImageView) findViewById(R.id.vector_ek581);
		vector_ek582 = (ImageView) findViewById(R.id.vector_ek582);
		vector_ek583 = (ImageView) findViewById(R.id.vector_ek583);
		vector_ek584 = (ImageView) findViewById(R.id.vector_ek584);
		vector_ek585 = (ImageView) findViewById(R.id.vector_ek585);
		vector_ek586 = (ImageView) findViewById(R.id.vector_ek586);
		vector_ek587 = (ImageView) findViewById(R.id.vector_ek587);
		vector_ek588 = (ImageView) findViewById(R.id.vector_ek588);
		_bg__group_ek145 = (View) findViewById(R.id._bg__group_ek145);
		vector_ek589 = (ImageView) findViewById(R.id.vector_ek589);
		_bg__group_ek147 = (View) findViewById(R.id._bg__group_ek147);
		vector_ek590 = (ImageView) findViewById(R.id.vector_ek590);
		vector_ek591 = (ImageView) findViewById(R.id.vector_ek591);
		vector_ek592 = (ImageView) findViewById(R.id.vector_ek592);
		tp = (TextView) findViewById(R.id.tp);
		x_1_ek5 = (ImageView) findViewById(R.id.x_1_ek5);
		rectangle_32_ek6 = (ImageView) findViewById(R.id.rectangle_32_ek6);
		academics_ek4 = (TextView) findViewById(R.id.academics_ek4);
		classroom = (TextView) findViewById(R.id.classroom);
		discover_ek7 = (TextView) findViewById(R.id.discover_ek7);
		profile_ek8 = (TextView) findViewById(R.id.profile_ek8);
		_bg__group_52_ek15 = (View) findViewById(R.id._bg__group_52_ek15);
		vector_ek593 = (ImageView) findViewById(R.id.vector_ek593);
		vector_ek594 = (ImageView) findViewById(R.id.vector_ek594);
		vector_ek595 = (ImageView) findViewById(R.id.vector_ek595);
		vector_ek596 = (ImageView) findViewById(R.id.vector_ek596);
	
		
		//custom code goes here
	
	}
}
	
	