
	 
	/*
	 *	This content is generated from the API File Info.
	 *	(Alt+Shift+Ctrl+I).
	 *
	 *	@desc 		
	 *	@file 		enter_id
	 *	@date 		Thursday 25th of April 2024 10:03:48 AM
	 *	@title 		Page 1
	 *	@author 	
	 *	@keywords 	
	 *	@generator 	Export Kit v1.3.figma
	 *
	 */


	package pfe.africar.activitys;

import android.app.Activity;
import android.os.Bundle;


import android.view.View;
import android.widget.TextView;
import android.widget.ImageView;

import pfe.africar.R;

	public class list_eleve__activity extends Activity {

	
	private View _bg__list_eleve__ek2;
	private TextView classroom_lists_ek4;
	private View _bg__frame_141_ek3;
	private TextView add_new_student;
	private View _bg__frame_128_ek3;
	private ImageView vector_ek652;
	private View _bg__frame_155_ek1;
	private TextView update_timetable;
	private View _bg__frame_128_ek5;
	private ImageView vector_ek653;
	private View _bg__frame_156_ek1;
	private View _bg__frame_189_ek1;
	private View _bg__frame_154_ek1;
	private TextView foulen_el_fouleni;
	private TextView __123456789;
	private View _bg__healthicons_i_exam_qualification_outline_ek1;
	private View _bg__group_ek151;
	private ImageView vector_ek654;
	private ImageView vector_ek655;
	private ImageView vector_ek656;
	private ImageView vector_ek657;
	private ImageView line_14;
	private View _bg__frame_158_ek1;
	private View _bg__frame_191_ek1;
	private View _bg__frame_154_ek3;
	private TextView foulen_el_fouleni_ek1;
	private TextView __123456789_ek1;
	private View _bg__healthicons_i_exam_qualification_outline_ek3;
	private View _bg__group_ek153;
	private ImageView vector_ek658;
	private ImageView vector_ek659;
	private ImageView vector_ek660;
	private ImageView vector_ek661;
	private ImageView line_14_ek1;
	private View _bg__frame_160_ek1;
	private View _bg__frame_193_ek1;
	private View _bg__frame_154_ek5;
	private TextView foulen_el_fouleni_ek2;
	private TextView __123456789_ek2;
	private View _bg__healthicons_i_exam_qualification_outline_ek5;
	private View _bg__group_ek155;
	private ImageView vector_ek662;
	private ImageView vector_ek663;
	private ImageView vector_ek664;
	private ImageView vector_ek665;
	private ImageView line_14_ek2;
	private View _bg__frame_162_ek1;
	private View _bg__frame_195_ek1;
	private View _bg__frame_154_ek7;
	private TextView foulen_el_fouleni_ek3;
	private TextView __123456789_ek3;
	private View _bg__healthicons_i_exam_qualification_outline_ek7;
	private View _bg__group_ek157;
	private ImageView vector_ek666;
	private ImageView vector_ek667;
	private ImageView vector_ek668;
	private ImageView vector_ek669;
	private ImageView line_14_ek3;
	private View _bg__frame_164_ek1;
	private View _bg__frame_197_ek1;
	private View _bg__frame_154_ek9;
	private TextView foulen_el_fouleni_ek4;
	private TextView __123456789_ek4;
	private View _bg__healthicons_i_exam_qualification_outline_ek9;
	private View _bg__group_ek159;
	private ImageView vector_ek670;
	private ImageView vector_ek671;
	private ImageView vector_ek672;
	private ImageView vector_ek673;
	private ImageView line_14_ek4;
	private View _bg__frame_166_ek1;
	private View _bg__frame_188_ek1;
	private View _bg__frame_154_ek11;
	private TextView foulen_el_fouleni_ek5;
	private TextView __123456789_ek5;
	private View _bg__healthicons_i_exam_qualification_outline_ek11;
	private View _bg__group_ek161;
	private ImageView vector_ek674;
	private ImageView vector_ek675;
	private ImageView vector_ek676;
	private ImageView vector_ek677;
	private ImageView line_14_ek5;
	private View _bg__frame_168_ek1;
	private View _bg__frame_200_ek1;
	private View _bg__frame_154_ek13;
	private TextView foulen_el_fouleni_ek6;
	private TextView __123456789_ek6;
	private View _bg__healthicons_i_exam_qualification_outline_ek13;
	private View _bg__group_ek163;
	private ImageView vector_ek678;
	private ImageView vector_ek679;
	private ImageView vector_ek680;
	private ImageView vector_ek681;
	private ImageView line_14_ek6;
	private View _bg__frame_170_ek1;
	private View _bg__frame_202_ek1;
	private View _bg__frame_154_ek15;
	private TextView foulen_el_fouleni_ek7;
	private TextView __123456789_ek7;
	private View _bg__healthicons_i_exam_qualification_outline_ek15;
	private View _bg__group_ek165;
	private ImageView vector_ek682;
	private ImageView vector_ek683;
	private ImageView vector_ek684;
	private ImageView vector_ek685;
	private ImageView line_14_ek7;
	private View _bg__frame_172_ek1;
	private View _bg__frame_154_ek17;
	private TextView foulen_el_fouleni_ek8;
	private TextView __123456789_ek8;
	private ImageView line_14_ek8;
	private View _bg__frame_157_ek1;
	private View _bg__frame_190_ek1;
	private View _bg__frame_154_ek19;
	private TextView foulen_el_fouleni_ek9;
	private TextView __123456789_ek9;
	private View _bg__healthicons_i_exam_qualification_outline_ek17;
	private View _bg__group_ek167;
	private ImageView vector_ek686;
	private ImageView vector_ek687;
	private ImageView vector_ek688;
	private ImageView vector_ek689;
	private ImageView line_14_ek9;
	private View _bg__frame_159_ek1;
	private View _bg__frame_192_ek1;
	private View _bg__frame_154_ek21;
	private TextView foulen_el_fouleni_ek10;
	private TextView __123456789_ek10;
	private View _bg__healthicons_i_exam_qualification_outline_ek19;
	private View _bg__group_ek169;
	private ImageView vector_ek690;
	private ImageView vector_ek691;
	private ImageView vector_ek692;
	private ImageView vector_ek693;
	private ImageView line_14_ek10;
	private View _bg__frame_161_ek1;
	private View _bg__frame_194_ek1;
	private View _bg__frame_154_ek23;
	private TextView foulen_el_fouleni_ek11;
	private TextView __123456789_ek11;
	private View _bg__healthicons_i_exam_qualification_outline_ek21;
	private View _bg__group_ek171;
	private ImageView vector_ek694;
	private ImageView vector_ek695;
	private ImageView vector_ek696;
	private ImageView vector_ek697;
	private ImageView line_14_ek11;
	private View _bg__frame_163_ek1;
	private View _bg__frame_196_ek1;
	private View _bg__frame_154_ek25;
	private TextView foulen_el_fouleni_ek12;
	private TextView __123456789_ek12;
	private View _bg__healthicons_i_exam_qualification_outline_ek23;
	private View _bg__group_ek173;
	private ImageView vector_ek698;
	private ImageView vector_ek699;
	private ImageView vector_ek700;
	private ImageView vector_ek701;
	private ImageView line_14_ek12;
	private View _bg__frame_165_ek1;
	private View _bg__frame_198_ek1;
	private View _bg__frame_154_ek27;
	private TextView foulen_el_fouleni_ek13;
	private TextView __123456789_ek13;
	private View _bg__healthicons_i_exam_qualification_outline_ek25;
	private View _bg__group_ek175;
	private ImageView vector_ek702;
	private ImageView vector_ek703;
	private ImageView vector_ek704;
	private ImageView vector_ek705;
	private ImageView line_14_ek13;
	private View _bg__frame_167_ek1;
	private View _bg__frame_199_ek1;
	private View _bg__frame_154_ek29;
	private TextView foulen_el_fouleni_ek14;
	private TextView __123456789_ek14;
	private View _bg__healthicons_i_exam_qualification_outline_ek27;
	private View _bg__group_ek177;
	private ImageView vector_ek706;
	private ImageView vector_ek707;
	private ImageView vector_ek708;
	private ImageView vector_ek709;
	private ImageView line_14_ek14;
	private View _bg__frame_169_ek1;
	private View _bg__frame_201_ek1;
	private View _bg__frame_154_ek31;
	private TextView foulen_el_fouleni_ek15;
	private TextView __123456789_ek15;
	private View _bg__healthicons_i_exam_qualification_outline_ek29;
	private View _bg__group_ek179;
	private ImageView vector_ek710;
	private ImageView vector_ek711;
	private ImageView vector_ek712;
	private ImageView vector_ek713;
	private ImageView line_14_ek15;
	private View _bg__frame_171_ek1;
	private View _bg__frame_154_ek33;
	private TextView foulen_el_fouleni_ek16;
	private TextView __123456789_ek16;
	private ImageView line_14_ek16;
	private View _bg__frame_173_ek1;
	private View _bg__frame_154_ek35;
	private TextView foulen_el_fouleni_ek17;
	private TextView __123456789_ek17;
	private ImageView line_14_ek17;
	private ImageView x_1_ek15;
	private ImageView rectangle_32_ek15;
	private TextView updates_ek2;
	private TextView personnel_ek2;
	private TextView stats_ek2;
	private TextView school_ek2;
	private ImageView vector_ek714;
	private ImageView vector_ek715;
	private ImageView vector_ek716;
	private ImageView vector_ek717;

	@Override
	public void onCreate(Bundle savedInstanceState) {

		super.onCreate(savedInstanceState);
		setContentView(R.layout.list_eleve_);

		
		_bg__list_eleve__ek2 = (View) findViewById(R.id._bg__list_eleve__ek2);
		classroom_lists_ek4 = (TextView) findViewById(R.id.classroom_lists_ek4);
		_bg__frame_141_ek3 = (View) findViewById(R.id._bg__frame_141_ek3);
		add_new_student = (TextView) findViewById(R.id.add_new_student);
		_bg__frame_128_ek3 = (View) findViewById(R.id._bg__frame_128_ek3);
		vector_ek652 = (ImageView) findViewById(R.id.vector_ek652);
		_bg__frame_155_ek1 = (View) findViewById(R.id._bg__frame_155_ek1);
		update_timetable = (TextView) findViewById(R.id.update_timetable);
		_bg__frame_128_ek5 = (View) findViewById(R.id._bg__frame_128_ek5);
		vector_ek653 = (ImageView) findViewById(R.id.vector_ek653);
		_bg__frame_156_ek1 = (View) findViewById(R.id._bg__frame_156_ek1);
		_bg__frame_189_ek1 = (View) findViewById(R.id._bg__frame_189_ek1);
		_bg__frame_154_ek1 = (View) findViewById(R.id._bg__frame_154_ek1);
		foulen_el_fouleni = (TextView) findViewById(R.id.foulen_el_fouleni);
		__123456789 = (TextView) findViewById(R.id.__123456789);
		_bg__healthicons_i_exam_qualification_outline_ek1 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek1);
		_bg__group_ek151 = (View) findViewById(R.id._bg__group_ek151);
		vector_ek654 = (ImageView) findViewById(R.id.vector_ek654);
		vector_ek655 = (ImageView) findViewById(R.id.vector_ek655);
		vector_ek656 = (ImageView) findViewById(R.id.vector_ek656);
		vector_ek657 = (ImageView) findViewById(R.id.vector_ek657);
		line_14 = (ImageView) findViewById(R.id.line_14);
		_bg__frame_158_ek1 = (View) findViewById(R.id._bg__frame_158_ek1);
		_bg__frame_191_ek1 = (View) findViewById(R.id._bg__frame_191_ek1);
		_bg__frame_154_ek3 = (View) findViewById(R.id._bg__frame_154_ek3);
		foulen_el_fouleni_ek1 = (TextView) findViewById(R.id.foulen_el_fouleni_ek1);
		__123456789_ek1 = (TextView) findViewById(R.id.__123456789_ek1);
		_bg__healthicons_i_exam_qualification_outline_ek3 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek3);
		_bg__group_ek153 = (View) findViewById(R.id._bg__group_ek153);
		vector_ek658 = (ImageView) findViewById(R.id.vector_ek658);
		vector_ek659 = (ImageView) findViewById(R.id.vector_ek659);
		vector_ek660 = (ImageView) findViewById(R.id.vector_ek660);
		vector_ek661 = (ImageView) findViewById(R.id.vector_ek661);
		line_14_ek1 = (ImageView) findViewById(R.id.line_14_ek1);
		_bg__frame_160_ek1 = (View) findViewById(R.id._bg__frame_160_ek1);
		_bg__frame_193_ek1 = (View) findViewById(R.id._bg__frame_193_ek1);
		_bg__frame_154_ek5 = (View) findViewById(R.id._bg__frame_154_ek5);
		foulen_el_fouleni_ek2 = (TextView) findViewById(R.id.foulen_el_fouleni_ek2);
		__123456789_ek2 = (TextView) findViewById(R.id.__123456789_ek2);
		_bg__healthicons_i_exam_qualification_outline_ek5 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek5);
		_bg__group_ek155 = (View) findViewById(R.id._bg__group_ek155);
		vector_ek662 = (ImageView) findViewById(R.id.vector_ek662);
		vector_ek663 = (ImageView) findViewById(R.id.vector_ek663);
		vector_ek664 = (ImageView) findViewById(R.id.vector_ek664);
		vector_ek665 = (ImageView) findViewById(R.id.vector_ek665);
		line_14_ek2 = (ImageView) findViewById(R.id.line_14_ek2);
		_bg__frame_162_ek1 = (View) findViewById(R.id._bg__frame_162_ek1);
		_bg__frame_195_ek1 = (View) findViewById(R.id._bg__frame_195_ek1);
		_bg__frame_154_ek7 = (View) findViewById(R.id._bg__frame_154_ek7);
		foulen_el_fouleni_ek3 = (TextView) findViewById(R.id.foulen_el_fouleni_ek3);
		__123456789_ek3 = (TextView) findViewById(R.id.__123456789_ek3);
		_bg__healthicons_i_exam_qualification_outline_ek7 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek7);
		_bg__group_ek157 = (View) findViewById(R.id._bg__group_ek157);
		vector_ek666 = (ImageView) findViewById(R.id.vector_ek666);
		vector_ek667 = (ImageView) findViewById(R.id.vector_ek667);
		vector_ek668 = (ImageView) findViewById(R.id.vector_ek668);
		vector_ek669 = (ImageView) findViewById(R.id.vector_ek669);
		line_14_ek3 = (ImageView) findViewById(R.id.line_14_ek3);
		_bg__frame_164_ek1 = (View) findViewById(R.id._bg__frame_164_ek1);
		_bg__frame_197_ek1 = (View) findViewById(R.id._bg__frame_197_ek1);
		_bg__frame_154_ek9 = (View) findViewById(R.id._bg__frame_154_ek9);
		foulen_el_fouleni_ek4 = (TextView) findViewById(R.id.foulen_el_fouleni_ek4);
		__123456789_ek4 = (TextView) findViewById(R.id.__123456789_ek4);
		_bg__healthicons_i_exam_qualification_outline_ek9 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek9);
		_bg__group_ek159 = (View) findViewById(R.id._bg__group_ek159);
		vector_ek670 = (ImageView) findViewById(R.id.vector_ek670);
		vector_ek671 = (ImageView) findViewById(R.id.vector_ek671);
		vector_ek672 = (ImageView) findViewById(R.id.vector_ek672);
		vector_ek673 = (ImageView) findViewById(R.id.vector_ek673);
		line_14_ek4 = (ImageView) findViewById(R.id.line_14_ek4);
		_bg__frame_166_ek1 = (View) findViewById(R.id._bg__frame_166_ek1);
		_bg__frame_188_ek1 = (View) findViewById(R.id._bg__frame_188_ek1);
		_bg__frame_154_ek11 = (View) findViewById(R.id._bg__frame_154_ek11);
		foulen_el_fouleni_ek5 = (TextView) findViewById(R.id.foulen_el_fouleni_ek5);
		__123456789_ek5 = (TextView) findViewById(R.id.__123456789_ek5);
		_bg__healthicons_i_exam_qualification_outline_ek11 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek11);
		_bg__group_ek161 = (View) findViewById(R.id._bg__group_ek161);
		vector_ek674 = (ImageView) findViewById(R.id.vector_ek674);
		vector_ek675 = (ImageView) findViewById(R.id.vector_ek675);
		vector_ek676 = (ImageView) findViewById(R.id.vector_ek676);
		vector_ek677 = (ImageView) findViewById(R.id.vector_ek677);
		line_14_ek5 = (ImageView) findViewById(R.id.line_14_ek5);
		_bg__frame_168_ek1 = (View) findViewById(R.id._bg__frame_168_ek1);
		_bg__frame_200_ek1 = (View) findViewById(R.id._bg__frame_200_ek1);
		_bg__frame_154_ek13 = (View) findViewById(R.id._bg__frame_154_ek13);
		foulen_el_fouleni_ek6 = (TextView) findViewById(R.id.foulen_el_fouleni_ek6);
		__123456789_ek6 = (TextView) findViewById(R.id.__123456789_ek6);
		_bg__healthicons_i_exam_qualification_outline_ek13 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek13);
		_bg__group_ek163 = (View) findViewById(R.id._bg__group_ek163);
		vector_ek678 = (ImageView) findViewById(R.id.vector_ek678);
		vector_ek679 = (ImageView) findViewById(R.id.vector_ek679);
		vector_ek680 = (ImageView) findViewById(R.id.vector_ek680);
		vector_ek681 = (ImageView) findViewById(R.id.vector_ek681);
		line_14_ek6 = (ImageView) findViewById(R.id.line_14_ek6);
		_bg__frame_170_ek1 = (View) findViewById(R.id._bg__frame_170_ek1);
		_bg__frame_202_ek1 = (View) findViewById(R.id._bg__frame_202_ek1);
		_bg__frame_154_ek15 = (View) findViewById(R.id._bg__frame_154_ek15);
		foulen_el_fouleni_ek7 = (TextView) findViewById(R.id.foulen_el_fouleni_ek7);
		__123456789_ek7 = (TextView) findViewById(R.id.__123456789_ek7);
		_bg__healthicons_i_exam_qualification_outline_ek15 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek15);
		_bg__group_ek165 = (View) findViewById(R.id._bg__group_ek165);
		vector_ek682 = (ImageView) findViewById(R.id.vector_ek682);
		vector_ek683 = (ImageView) findViewById(R.id.vector_ek683);
		vector_ek684 = (ImageView) findViewById(R.id.vector_ek684);
		vector_ek685 = (ImageView) findViewById(R.id.vector_ek685);
		line_14_ek7 = (ImageView) findViewById(R.id.line_14_ek7);
		_bg__frame_172_ek1 = (View) findViewById(R.id._bg__frame_172_ek1);
		_bg__frame_154_ek17 = (View) findViewById(R.id._bg__frame_154_ek17);
		foulen_el_fouleni_ek8 = (TextView) findViewById(R.id.foulen_el_fouleni_ek8);
		__123456789_ek8 = (TextView) findViewById(R.id.__123456789_ek8);
		line_14_ek8 = (ImageView) findViewById(R.id.line_14_ek8);
		_bg__frame_157_ek1 = (View) findViewById(R.id._bg__frame_157_ek1);
		_bg__frame_190_ek1 = (View) findViewById(R.id._bg__frame_190_ek1);
		_bg__frame_154_ek19 = (View) findViewById(R.id._bg__frame_154_ek19);
		foulen_el_fouleni_ek9 = (TextView) findViewById(R.id.foulen_el_fouleni_ek9);
		__123456789_ek9 = (TextView) findViewById(R.id.__123456789_ek9);
		_bg__healthicons_i_exam_qualification_outline_ek17 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek17);
		_bg__group_ek167 = (View) findViewById(R.id._bg__group_ek167);
		vector_ek686 = (ImageView) findViewById(R.id.vector_ek686);
		vector_ek687 = (ImageView) findViewById(R.id.vector_ek687);
		vector_ek688 = (ImageView) findViewById(R.id.vector_ek688);
		vector_ek689 = (ImageView) findViewById(R.id.vector_ek689);
		line_14_ek9 = (ImageView) findViewById(R.id.line_14_ek9);
		_bg__frame_159_ek1 = (View) findViewById(R.id._bg__frame_159_ek1);
		_bg__frame_192_ek1 = (View) findViewById(R.id._bg__frame_192_ek1);
		_bg__frame_154_ek21 = (View) findViewById(R.id._bg__frame_154_ek21);
		foulen_el_fouleni_ek10 = (TextView) findViewById(R.id.foulen_el_fouleni_ek10);
		__123456789_ek10 = (TextView) findViewById(R.id.__123456789_ek10);
		_bg__healthicons_i_exam_qualification_outline_ek19 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek19);
		_bg__group_ek169 = (View) findViewById(R.id._bg__group_ek169);
		vector_ek690 = (ImageView) findViewById(R.id.vector_ek690);
		vector_ek691 = (ImageView) findViewById(R.id.vector_ek691);
		vector_ek692 = (ImageView) findViewById(R.id.vector_ek692);
		vector_ek693 = (ImageView) findViewById(R.id.vector_ek693);
		line_14_ek10 = (ImageView) findViewById(R.id.line_14_ek10);
		_bg__frame_161_ek1 = (View) findViewById(R.id._bg__frame_161_ek1);
		_bg__frame_194_ek1 = (View) findViewById(R.id._bg__frame_194_ek1);
		_bg__frame_154_ek23 = (View) findViewById(R.id._bg__frame_154_ek23);
		foulen_el_fouleni_ek11 = (TextView) findViewById(R.id.foulen_el_fouleni_ek11);
		__123456789_ek11 = (TextView) findViewById(R.id.__123456789_ek11);
		_bg__healthicons_i_exam_qualification_outline_ek21 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek21);
		_bg__group_ek171 = (View) findViewById(R.id._bg__group_ek171);
		vector_ek694 = (ImageView) findViewById(R.id.vector_ek694);
		vector_ek695 = (ImageView) findViewById(R.id.vector_ek695);
		vector_ek696 = (ImageView) findViewById(R.id.vector_ek696);
		vector_ek697 = (ImageView) findViewById(R.id.vector_ek697);
		line_14_ek11 = (ImageView) findViewById(R.id.line_14_ek11);
		_bg__frame_163_ek1 = (View) findViewById(R.id._bg__frame_163_ek1);
		_bg__frame_196_ek1 = (View) findViewById(R.id._bg__frame_196_ek1);
		_bg__frame_154_ek25 = (View) findViewById(R.id._bg__frame_154_ek25);
		foulen_el_fouleni_ek12 = (TextView) findViewById(R.id.foulen_el_fouleni_ek12);
		__123456789_ek12 = (TextView) findViewById(R.id.__123456789_ek12);
		_bg__healthicons_i_exam_qualification_outline_ek23 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek23);
		_bg__group_ek173 = (View) findViewById(R.id._bg__group_ek173);
		vector_ek698 = (ImageView) findViewById(R.id.vector_ek698);
		vector_ek699 = (ImageView) findViewById(R.id.vector_ek699);
		vector_ek700 = (ImageView) findViewById(R.id.vector_ek700);
		vector_ek701 = (ImageView) findViewById(R.id.vector_ek701);
		line_14_ek12 = (ImageView) findViewById(R.id.line_14_ek12);
		_bg__frame_165_ek1 = (View) findViewById(R.id._bg__frame_165_ek1);
		_bg__frame_198_ek1 = (View) findViewById(R.id._bg__frame_198_ek1);
		_bg__frame_154_ek27 = (View) findViewById(R.id._bg__frame_154_ek27);
		foulen_el_fouleni_ek13 = (TextView) findViewById(R.id.foulen_el_fouleni_ek13);
		__123456789_ek13 = (TextView) findViewById(R.id.__123456789_ek13);
		_bg__healthicons_i_exam_qualification_outline_ek25 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek25);
		_bg__group_ek175 = (View) findViewById(R.id._bg__group_ek175);
		vector_ek702 = (ImageView) findViewById(R.id.vector_ek702);
		vector_ek703 = (ImageView) findViewById(R.id.vector_ek703);
		vector_ek704 = (ImageView) findViewById(R.id.vector_ek704);
		vector_ek705 = (ImageView) findViewById(R.id.vector_ek705);
		line_14_ek13 = (ImageView) findViewById(R.id.line_14_ek13);
		_bg__frame_167_ek1 = (View) findViewById(R.id._bg__frame_167_ek1);
		_bg__frame_199_ek1 = (View) findViewById(R.id._bg__frame_199_ek1);
		_bg__frame_154_ek29 = (View) findViewById(R.id._bg__frame_154_ek29);
		foulen_el_fouleni_ek14 = (TextView) findViewById(R.id.foulen_el_fouleni_ek14);
		__123456789_ek14 = (TextView) findViewById(R.id.__123456789_ek14);
		_bg__healthicons_i_exam_qualification_outline_ek27 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek27);
		_bg__group_ek177 = (View) findViewById(R.id._bg__group_ek177);
		vector_ek706 = (ImageView) findViewById(R.id.vector_ek706);
		vector_ek707 = (ImageView) findViewById(R.id.vector_ek707);
		vector_ek708 = (ImageView) findViewById(R.id.vector_ek708);
		vector_ek709 = (ImageView) findViewById(R.id.vector_ek709);
		line_14_ek14 = (ImageView) findViewById(R.id.line_14_ek14);
		_bg__frame_169_ek1 = (View) findViewById(R.id._bg__frame_169_ek1);
		_bg__frame_201_ek1 = (View) findViewById(R.id._bg__frame_201_ek1);
		_bg__frame_154_ek31 = (View) findViewById(R.id._bg__frame_154_ek31);
		foulen_el_fouleni_ek15 = (TextView) findViewById(R.id.foulen_el_fouleni_ek15);
		__123456789_ek15 = (TextView) findViewById(R.id.__123456789_ek15);
		_bg__healthicons_i_exam_qualification_outline_ek29 = (View) findViewById(R.id._bg__healthicons_i_exam_qualification_outline_ek29);
		_bg__group_ek179 = (View) findViewById(R.id._bg__group_ek179);
		vector_ek710 = (ImageView) findViewById(R.id.vector_ek710);
		vector_ek711 = (ImageView) findViewById(R.id.vector_ek711);
		vector_ek712 = (ImageView) findViewById(R.id.vector_ek712);
		vector_ek713 = (ImageView) findViewById(R.id.vector_ek713);
		line_14_ek15 = (ImageView) findViewById(R.id.line_14_ek15);
		_bg__frame_171_ek1 = (View) findViewById(R.id._bg__frame_171_ek1);
		_bg__frame_154_ek33 = (View) findViewById(R.id._bg__frame_154_ek33);
		foulen_el_fouleni_ek16 = (TextView) findViewById(R.id.foulen_el_fouleni_ek16);
		__123456789_ek16 = (TextView) findViewById(R.id.__123456789_ek16);
		line_14_ek16 = (ImageView) findViewById(R.id.line_14_ek16);
		_bg__frame_173_ek1 = (View) findViewById(R.id._bg__frame_173_ek1);
		_bg__frame_154_ek35 = (View) findViewById(R.id._bg__frame_154_ek35);
		foulen_el_fouleni_ek17 = (TextView) findViewById(R.id.foulen_el_fouleni_ek17);
		__123456789_ek17 = (TextView) findViewById(R.id.__123456789_ek17);
		line_14_ek17 = (ImageView) findViewById(R.id.line_14_ek17);
		x_1_ek15 = (ImageView) findViewById(R.id.x_1_ek15);
		rectangle_32_ek15 = (ImageView) findViewById(R.id.rectangle_32_ek15);
		updates_ek2 = (TextView) findViewById(R.id.updates_ek2);
		personnel_ek2 = (TextView) findViewById(R.id.personnel_ek2);
		stats_ek2 = (TextView) findViewById(R.id.stats_ek2);
		school_ek2 = (TextView) findViewById(R.id.school_ek2);
		vector_ek714 = (ImageView) findViewById(R.id.vector_ek714);
		vector_ek715 = (ImageView) findViewById(R.id.vector_ek715);
		vector_ek716 = (ImageView) findViewById(R.id.vector_ek716);
		vector_ek717 = (ImageView) findViewById(R.id.vector_ek717);
	
		
		//custom code goes here
	
	}
}
	
	